#
# General OCaml build settings
#

OCAMLOPT = ocamlopt
OCAMLC = ocamlc
OCAMLDEP = ocamldep

OCAMLFLAGS =

%.cmi: %.mli
	$(OCAMLC) $(OCAMLFLAGS) -c $<

%.cmx: %.ml
	$(OCAMLOPT) $(OCAMLFLAGS) -c $<

%.cmo: %.ml
	$(OCAMLC) $(OCAMLFLAGS) -c $<

